sylvia/pruebas/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('inicio', views.index, name='index'),
    path('crear-pregunta', views.crear_pregunta, name='crear_pregunta'),
    path('crear-pregunta-procesar', views.crear_pregunta_procesar, name='crear_pregunta_procesar'),
    path('crear-prueba', views.crear_prueba, name='crear_prueba'),
    path('preguntas-guardadas', views.preguntas_guardadas, name='preguntas_guardadas'),
    path('crear-tag', views.crear_tags, name='crear_tag'),
    path('eliminar-tag/<int:tag_id>/', views.eliminar_tag, name='eliminar_tag'),
    path('guardar-tag', views.guardar_tags, name='guardar_tag'),
    path('salir', views.salir, name='salir'),
    path('generar-prueba', views.generar_prueba, name='generar_prueba'),
    path('editar/<int:unico_pregunta>/', views.preguntas_editadas, name="editar"),
    path('preguntas-guardadas-procesar', views.preguntas_guardadas_procesar, name='preguntas_guardadas_procesar'),
    path('guardar_pregunta_editada', views.guardar_pregunta_editada, name='guardar_pregunta_editada'),
    path('genera-pdf', views.generar_pdf, name='generar_pdf'),
    path('compartir', views.compartir, name='compartir'),
    path('compartir/usuario', views.compartir_usurio, name='compartir_usuario'),
    path('compartir/usuario/tags', views.guardar_compartidos_vista, name='guardar_compartido'),
    path('compartir/tabla-compartidos', views.tabla_compartidos, name='tabla_compartidos'),
    path('compartir/eliminar-permisos', views.eliminar_permiso, name='eliminar_permiso'),
    path('api/v1/<str:pregunta_numero>', views.api_traer_tag, name='api_traer_tag'),
    


    
    ]

sylvia/sylvia/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('l/', include("registro.urls")),
    path('dentro/',include("pruebas.urls")),
]

sylvia/pruebas/models.py
from django.db import models
from registro.models import *
from django.contrib.auth.models import User
from random import shuffle

class TagModel(models.Model):
    id_tag=models.AutoField(primary_key=True)
    usuario=models.ForeignKey(User,on_delete=models.CASCADE,null=True)
    tema=models.CharField(null=True, max_length=20)
    def todos(self,request):
        todo=self.Objects.filter(usuario=request.user)
        return todo
    def __str__(self):
        return self.tema

#este model crea la pregunta que puede ser utilizada en cualquier parte



class PreguntaModel(models.Model):
    usuario=models.ForeignKey(User,on_delete=models.CASCADE,null=True)
    tag=models.ManyToManyField(TagModel)
    unico_pregunta=models.AutoField(primary_key=True)
    enunciado = models.TextField()
    explicacion = models.TextField(null=True)
    
    
    def todos(self,request):
        todo=self.objects.filter(usuario=request.user)
        return todo
    def __str__(self):
        return self.enunciado

class AlternativaModel(models.Model):
    id_alternativa = models.AutoField(primary_key=True)
    texto = models.TextField()
    es_correcta = models.BooleanField(default=False)
    dibujo = models.TextField(null=True)
    enunciado_alternativa = models.ForeignKey(PreguntaModel,on_delete=models.CASCADE,null=True)

    
#Este especifica el comportamiento de la pregunta dentro de la prueba.
#si será pregunta fija, si será única, etc.
class PreguntaPruebaModel(models.Model):
    usuario=models.ForeignKey(User,on_delete=models.CASCADE,null=True)
    unico_pregunta_prueba=models.AutoField(primary_key=True)
    pregunta=models.ForeignKey(PreguntaModel,on_delete=models.CASCADE)
    p_fija=models.BooleanField()
    p_usar=models.BooleanField()

#Este model crea la prueba en genera, la engloba.
class PruebaModel(models.Model):
    usuario=models.ForeignKey(User,on_delete=models.CASCADE,null=True)
    unico_prueba=models.AutoField(primary_key=True)
    pregunta_prueba=models.ForeignKey(PreguntaPruebaModel,on_delete=models.CASCADE,null=True)
    fila=models.TextField(null=True)
    fecha=models.DateTimeField(null=True)
    materia=models.TextField(null=True)
    curso=models.TextField(null=True)
    fecha_timbre=models.DateTimeField(auto_now=True,null=False)


class CompartirModel(models.Model):
    numero_compartido = models.AutoField(primary_key=True)
    yo = models.IntegerField(null=True)
    usuario_a_compartir = models.ForeignKey(User,on_delete=models.CASCADE,null=True)
    tag_a_compartir = models.ForeignKey(TagModel,on_delete=models.CASCADE,null=True)




#acá debería ir despues: materias, profesores y colegios.

sylvia/pruebas/views.py
from django.forms import modelformset_factory,formset_factory,inlineformset_factory
from django.shortcuts import render,redirect
from django.http import HttpResponse,JsonResponse,FileResponse
from .models import PreguntaModel,PruebaModel,AlternativaModel
from pruebas.formularios import *
from django.contrib.auth.models import User
from django.core import serializers
from .funciones_externas import motor,PreguntaFinal
import json
import os

def index(request):
    usuario=request.user
    print('Dentro del index',usuario)
    return render(request,'pruebas/index.html',{'usuario':usuario})



def crear_pregunta(request):
    context={}
    AlternativasFormSet = formset_factory(AlternativaForm,extra=5, formset=PreguntaCompletaFormset) #el PreguntaCompletaFormset es para validar el formulario
    context['crear_pregunta_formulario']=CrearPreguntaForm(user=request.user) #Crea el encabezado
    context['formulario_alternativas'] = AlternativasFormSet() #Crea un paquete de 5 preguntas
    
    return render(request,'pruebas/crear_pregunta.html',context)

def crear_pregunta_procesar(request):
    context={}
    if request.method == 'POST':
        form = CrearPreguntaForm(request.POST,user=request.user) #creamos el enunciado
        AlternativasFormSet = formset_factory(AlternativaForm,extra=5,formset=PreguntaCompletaFormset) #crea un paquete de 5 formularios tipo alternativa
        formularioAlternativa = AlternativasFormSet(request.POST or None)
        if form.is_valid() and formularioAlternativa.is_valid():
            #pregunta_enunciado = form.cleaned_data['enunciado']
            pregunta_tag = form.cleaned_data['tag']
            fs = form.save(commit=False)
            fs.usuario=request.user
            fs.save()
            fs.tag.set(pregunta_tag) #método set para asignar manytomany, debemos antes guardar el formulario
            
            for f in formularioAlternativa:
                alternativa_texto = f.cleaned_data['texto']
                alternativa_correcta = f.cleaned_data['es_correcta']
                Alternativa = AlternativaModel(
                    texto = alternativa_texto,
                    es_correcta = alternativa_correcta,
                    enunciado_alternativa = fs
                    )
                Alternativa.save()
            return redirect('crear_pregunta')
        else:
            #mandamos los formularios devuelta a la vista con los errores en él
            context['formulario_alternativas'] = formularioAlternativa
            context['crear_pregunta_formulario']=form
            return render(request,'pruebas/crear_pregunta.html',context)

    return render(request,'pruebas/crear_pregunta.html',context)



def crear_prueba(request):
    data = {}
    data['crear_prueba_formulario'] = CrearPruebaForm()
    tag_compartidos = CompartirModel.objects.filter(usuario_a_compartir = request.user).values_list('tag_a_compartir') or None
    data['preguntas'] = PreguntaModel.objects.filter(usuario=request.user).order_by('unico_pregunta')
    if tag_compartidos:
        preguntas_compartidas = PreguntaModel.objects.filter(tag__in = tag_compartidos)
        data['preguntas_compartidas'] = preguntas_compartidas
    
    return render(request,'pruebas/crear-prueba.html',data)


def preguntas_guardadas(request):
    data = {}
    tag_compartidos = CompartirModel.objects.filter(usuario_a_compartir = request.user).values_list('tag_a_compartir') or None
    preguntas = PreguntaModel.objects.filter(usuario=request.user).order_by('unico_pregunta')
    data['preguntas'] = preguntas
    if tag_compartidos:
        preguntas_compartidas = PreguntaModel.objects.filter(tag__in = tag_compartidos)
        data['preguntas_compartidas'] = preguntas_compartidas
    return render(request,'pruebas/preguntas-guardadas.html',data)

def salir(request):
    request.session.flush()
    return redirect('login_inicial')

def crear_tags(request):
    crear_tags_formulario=CrearTagsForm()
    #vemos las etiquetas creadas
    etiquetas=TagModel.objects.filter(usuario=request.user)
    etiquetas_externas=CompartirModel.objects.filter(usuario_a_compartir=request.user.id)
    return render(request,'pruebas/tags.html',{'crear_tags_formulario':crear_tags_formulario,'etiquetas':etiquetas,'etiquetas_externas':etiquetas_externas})

def guardar_tags(request):
    context={}
    if request.method == 'POST':
       
        form = CrearTagsForm(request.POST)
        if form.is_valid():
            fs=form.save(commit=False)
            tema = form.cleaned_data['tema']
            fs.tema=tema
            fs.usuario=request.user
            fs.save()
            return redirect('crear_tag')

    # if a GET (or any other method) we'll create a blank form
        else:
            print('Hay un error en el formulario')
            return redirect('crear_tags')

    return render(request,'pruebas/crear_pregunta.html',context) 

def procesar(request):
    if request.method == 'POST':
        algo=request.POST.copy()
    return HttpResponse('procesar')


def preguntas_guardadas_procesar(request):
    if request.method == 'POST':
        preguntas_edit=request.POST.copy()
        if preguntas_edit['accion']=='Borrar':
            pregunta_borrar=PreguntaModel.objects.get(usuario=request.user,unico_pregunta=preguntas_edit['pregunta_numero'])
            pregunta_borrar.delete()
            return redirect('preguntas_guardadas')
        

def preguntas_editadas(request,unico_pregunta):
    context={}
    context['unico_pregunta']=unico_pregunta
    FormularioAlternativa = inlineformset_factory(
        PreguntaModel,
        AlternativaModel,
        fields=('texto','es_correcta','enunciado_alternativa'), 
        extra=0,
        can_delete=False
    )
    enunciado = PreguntaModel.objects.get(unico_pregunta=unico_pregunta,usuario=request.user)
    tags = PreguntaModel.objects.filter(unico_pregunta=unico_pregunta).values('tag')
    context['editar_enunciado_formulario']=CrearPreguntaForm(
        instance=enunciado,
        user=request.user,
        # initial={
        #     'tag':tags
        # }
        )
    context['editar_formulario_alternativas'] = FormularioAlternativa(instance=enunciado)
    
    return render(request,'pruebas/editar_pregunta.html',context)

def guardar_pregunta_editada(request):
    copia=request.POST.copy()
    tags = request.POST.getlist("tag")

    enunciado = PreguntaModel.objects.get(unico_pregunta=copia['unico'])
    enunciado.tag.set(tags)
    
    if request.method=="POST" and copia['accion']=='Actualizar':
        FormularioAlternativaClass = inlineformset_factory(
            PreguntaModel,
            AlternativaModel,
            fields=('texto','es_correcta'),
            extra=0,
            can_delete = False,
            formset=PreguntaCompletaFormsetEditada
            )
        Enunciado_desde_form = EnunciadoForm(request.POST, instance=enunciado)
        #Enunciado_desde_form = EnunciadoForm(request.POST)
        formularioAlternativa = FormularioAlternativaClass(request.POST,instance=enunciado)
        #formularioAlternativa = FormularioAlternativaClass(request.POST)
        if Enunciado_desde_form.is_valid() and formularioAlternativa.is_valid():
            Enunciado_desde_form.save()
            formularioAlternativa.save()
        else:
            context={}
            FormularioAlternativa = inlineformset_factory(PreguntaModel,AlternativaModel,fields=('texto','es_correcta','enunciado_alternativa'), extra=0,can_delete=False)
            context['editar_formulario_alternativas'] = FormularioAlternativa(instance=enunciado)
            context['editar_enunciado_formulario']=EnunciadoForm(instance=enunciado)
            return render(request,'pruebas/editar_pregunta.html',context)
    return redirect('preguntas_guardadas')


def generar_prueba(request):
    encabezado_jason={}
    configuracion_prueba=request.POST.copy()
    preguntas_seleccionadas=[]
    preguntas_fijas=[]
    cantidad_filas=int(configuracion_prueba['CantidadFilas'])
    cantidad_preguntas=int(configuracion_prueba['CantidadPreguntas'])
    encabezado_jason['curso']=configuracion_prueba['curso']
    encabezado_jason['nombre_prueba']=configuracion_prueba['nombre_prueba']
    for k,v in configuracion_prueba.items():
        if v=='on' and k.isdigit():
            preguntas_seleccionadas.append(k)
        if v=='on' and k.startswith('fija_'):
            fija=k.strip('fija_')
            preguntas_fijas.append(fija)
    contenedor=motor(
        POOL_DE_PREGUNTAS=preguntas_seleccionadas,
    CANTIDAD_FILAS=cantidad_filas,
    PREGUNTAS_FIJAS=preguntas_fijas,
    CANTIDAD_PREGUNTAS=cantidad_preguntas
    )
    contenedor_final=[]
    enumeracion_preguntas = [n for n in range(1,cantidad_preguntas+1)]
    pruebas = {}
    m = 0
    for i in contenedor:
        contenedor_auxiliar = [] # Preview
        contenedor_json=[] # Latex
        m = m+1 #latex
        for j in i:
            p = PreguntaFinal(id_prueba=j)
            contenedor_json.append(p.serializado()) # Latex
            contenedor_auxiliar.append(p) # Preview
            contenedor_auxiliar_2=zip(enumeracion_preguntas,contenedor_auxiliar) # Preview
        pruebas[str(m)]=contenedor_json # Latex
        contenedor_final.append(contenedor_auxiliar_2) # Preview
    pruebas['encabezado'] = encabezado_jason
    pruebas['cantidad_preguntas']=cantidad_preguntas
    request.session['contenedor']=pruebas
    
    return render(request,'pruebas/preview-prueba.html',{'contenedor_final':contenedor_final})


def generar_pdf(request):
    #aca habría que poner donde borrar los archivos si es que existen antes de rellenarlos
    os.system("rm p*.*")
    prueba = request.session.get('contenedor')
    cantidad_preguntas=prueba['cantidad_preguntas']
    archivo_salida = open("prueba.tex","w")
    archivo_salida.write("\\documentclass[10pt,oneside,letterpaper]{article}")
    archivo_salida.write("\\usepackage[utf8x]{inputenc}")

sylvia/pruebas/templates/pruebas/compartir.html
{% extends './index.html' %}


{% block contenidos %}
<h3>Estamos en compartir </h3>
<form action="{% url 'guardar_compartido' %}" method="post">
    {% csrf_token %}
    {{ formulario_compartir }}
    <input type="submit" class="btn btn-success mt-2" value="Agregar">
</form>

<h2>Se han compartido los siguientes tags</h2>
<div id="compartidos">

  <table class="table">
    <thead>
      <tr>
        <th>A quien</th>
        <th>Hoy</th>
        <th>Acciones</th>

      </tr>
    </thead>
    <tbody>
      {% for t in tabla_compartidos %}
      <tr>

        <td>{{ t.usuario_a_compartir}}</td>
        <td>{{ t.tag_a_compartir}}</td>
        <td>
          <form action="{% url 'eliminar_permiso' %}" method="POST">
            {% csrf_token %}
            <input type="hidden" name='id' value="{{t.numero_compartido}}">
            <input type="submit" class="btn btn-danger" value="Eliminar">
          </form>
        </td>
      
      </tr>
      {% endfor %}
      </tbody>
  </table>
</div>


<script>
    
    $(function() {
    $( "#id_usuario_a_compartir" ).autocomplete({
        source: "{% url 'compartir_usuario' %}",
        
        });
    });

</script>

{% endblock %}

sylvia/pruebas/templates/pruebas/crear-prueba.html
{% extends './index.html' %}

{% block contenidos %}


<form action="{% url 'generar_prueba' %}" method="POST">
    {% csrf_token %}
    {{ crear_prueba_formulario }}
  <hr>
  <hr> 
<p>Seleccione las preguntas:</p>
<div class="row justify-content-center my-2">
  <input id="input_buscador" type="text" class="form-control col-lg-6" placeholder="buscar..." onkeyup="Buscar()">
  
</div>
  
  <table class="table" >
    <thead class="thead-light">
      <tr id="pregunta">
        <th scope="col">#</th>
        <th scope="col">Usar</th>
        <th scope="col">Enunciado</th>

        <th scope="col">Fija</th>
        <th scope="col">Tag</th>
      </tr>
    </thead>
    <tbody id="preguntas">
      {% if preguntas %}
      {% for pregunta in preguntas %}
      <tr>
        <th scope="row">1</th>
        <td>
          <div class="form-group form-check">
          <input type="checkbox" name="{{ pregunta.unico_pregunta }}" class="form-check-input" id="exampleCheck1">
          <label class="form-check-label"  for="exampleCheck1">Usar</label>
            </div>
          </td>
        <td>{{ pregunta.enunciado }}</td>
        <td>
            <div class="form-group form-check">
            <input type="checkbox" name="fija_{{ pregunta.unico_pregunta }}" class="form-check-input" id="exampleCheck1">
            <label class="form-check-label"  for="exampleCheck1">Dejar pregunta fija</label>
              </div>
          </td>
          <td>
            {{ pregunta.tag}}
            </td>
      </tr>
      {% endfor %}
      {% endif %}
      {% if preguntas_compartidas %}

      {% for pregunta in preguntas_compartidas %}
      <tr class="bg-warning">
        <th scope="row">1</th>
        <td>
          <div class="form-group form-check">
          <input type="checkbox" name="{{ pregunta.unico_pregunta }}" class="form-check-input" id="exampleCheck1">
          <label class="form-check-label"  for="exampleCheck1">Usar</label>
            </div>
          </td>
        <td>{{ pregunta.enunciado }}</td>
        <td>
            <div class="form-group form-check">
            <input type="checkbox" name="fija_{{ pregunta.unico_pregunta }}" class="form-check-input" id="exampleCheck1">
            <label class="form-check-label"  for="exampleCheck1">Dejar pregunta fija</label>
              </div>
          </td>
          <td>
            {{ pregunta.tag }}
            </td>
      </tr>
      {% endfor %}
    
      {% endif%}



    </tbody>
  </table>
  <input type="submit" class="btn btn-info" value="Generar">
</form>
<script>
  function Buscar() {
    // Declare variables
    var input, filter, ul, li, a, i, txtValue;
    input = document.getElementById('input_buscador');
    filter = input.value.toUpperCase();
    ul = document.getElementById("preguntas");
    tr = ul.getElementsByTagName('tr');
    for (i = 0; i < tr.length; i++) {
      a = tr[i].getElementsByTagName("td")[1];
      txtValue = a.textContent || a.innerText;
      if (txtValue.toUpperCase().indexOf(filter) > -1) {
        tr[i].style.display = "";
      } else {
        tr[i].style.display = "none";
      }
    }
  }
  </script>
{% endblock %}

sylvia/pruebas/templates/pruebas/crear_pregunta.html
{% extends './index.html' %}

{% block contenidos %}
<h3 class="row">
    {{ formulario_alternativas.non_form_errors }}
    {{ crear_pregunta_formulario.non_form_errors }}

</h3>
<form action="{% url 'crear_pregunta_procesar' %}" method="post">
    {% csrf_token %}
    <div class="row">
        <div class="col-lg-6">
    {{ crear_pregunta_formulario.tag.label }}
        </div>
        <div class="col-lg-6">
    {{ crear_pregunta_formulario.tag }}
        </div>
    </div>
    <div class="row d-flex flex-column">
            <div class="p-2">
        {{ crear_pregunta_formulario.enunciado.label }}
            </div>
            <div class="p-2">
        {{ crear_pregunta_formulario.enunciado }}
            </div>
    </div>
    <div class="row d-flex flex-column">
        <div class="p-2">
        {{ crear_pregunta_formulario.explicacion.label }}
        </div>
        <div class="p-2">
        {{ crear_pregunta_formulario.explicacion }}
        </div>
    </div>
    <hr>
        
    
    {{ formulario_alternativas.management_form }}
     {% for f in formulario_alternativas %}
     <div class="row border p-2">
         <div class="row">
             <div class="col-lg-6">
                {{ f.texto.label }}
                {{ f.texto }}  
             </div>
             <div class="col-lg-6">
            {{ f.es_correcta.label }}
            {{ f.es_correcta }}
            </div>
         </div>
     
     <!-- {{ f.texto }} -->
     
    </div>

     {% endfor %}
 
    <input type="submit" class="btn btn-success mt-2" value="Submit">
</form>



{% endblock %}

sylvia/pruebas/templates/pruebas/editar_pregunta.html
{% extends './index.html' %}

{% block contenidos %}
<h3 class="row">
    {{ editar_formulario_alternativas.non_form_errors }}
    {{ editar_enunciado_formulario.non_form_errors }}

</h3>
<input type="hidden" id="numero_prgunta" value="{{ unico_pregunta }}">
<form action="{% url 'guardar_pregunta_editada' %}" method="post">
    {% csrf_token %}
    {{ editar_enunciado_formulario.management_form }}
    <div id="tags" class="row">
        <div class="col-lg-6">
    {{ editar_enunciado_formulario.tag.label }}
        </div>
        <div class="col-lg-6">
            {{ editar_enunciado_formulario.tag }}
        </div>
    </div>
 

    <div class="row d-flex flex-column">
        <div class="P-2">
            {{ editar_enunciado_formulario.enunciado.label }}
        </div>
        <div class="P-2">
            {{ editar_enunciado_formulario.enunciado }}
        </div>
    </div>
        <div class="row d-flex flex-column">
            <div class="p-2">
                {{ editar_enunciado_formulario.explicacion.label }}
            </div>
            <div class="p-2">
                {{ editar_enunciado_formulario.explicacion }}
            </div>
        </div>


    {{ editar_formulario_alternativas.management_form }}
    {% for f in editar_formulario_alternativas %}
    <!-- estas lineas de abajo es para que no levante error id_required -->
    {% for hidden in f.hidden_fields %}
        {{ hidden }}
    {% endfor %}
    <div class="row border p-2">
        <div class="row">
            <div class="col-lg-6">
               {{ f.texto.label }} 
               {{ f.texto }} 
            </div>
            <div class="col-lg-6">
           {{ f.es_correcta.label }}
           {{ f.es_correcta }}
           </div>
        </div>
            {{ f.id_alternativa}}

    
   </div>

    {% endfor %}
    
   
    <input type="hidden" name="unico" value="{{unico_pregunta}}">
    <input type="submit" class="btn btn-success mt-2" name="accion" value="Actualizar">
</form>

<script>
var numero_pregunta = document.getElementById("numero_prgunta");
var direccion = '/dentro/api/v1/' + numero_pregunta.value;
var listadom2m = document.getElementById('id_tag');
var opciones = listadom2m.options;
var opcion_array = Array.from(opciones, o => parseInt(o.value));
fetch(direccion)
.then(res => res.json())
.then(data => {
    var tags = data[0].fields['tag'];
    for (var i=0; i < opcion_array.length;i++){
        if (tags.includes(opcion_array[i])){
            opciones[i].selected = "selected";
        } else {
            console.log('else')
        };
    };
});
</script>

{% endblock %}

sylvia/pruebas/templates/pruebas/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

   
    
    <!-- <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>     -->
    <link rel="stylesheet" href="{% static 'js/jquery-ui-1.12.1.custom/jquery-ui.min.css' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery-ui-1.12.1.custom/jquery-ui.min.js' %}"></script>
    <!-- <script type="text/javascript" src="{% static 'js/pruebas.js' %}"></script> -->

    <title>Sylvia 1.0 - Generador de pruebas escritas</title>
   
</head>
<body>
<div class="container my-5">
        <div class="row border">
            <p>Sylvia 1.0v. Constructor de pruebas escritas</p><h3> {{ user.username }} -  {{ user.id }}  </h3>
        </div>
        
     
<div class="row">
<div class="col-3 border">
   
        <ul class="list-group">

                <a href="{% url 'index' %}">Inicio</a>
                <a href="{% url 'crear_prueba' %}">Crear prueba</a>
                <a href="{% url 'crear_pregunta' %}">Crear pregunta</a>
                <a href="{% url 'preguntas_guardadas' %}">Preguntas Guardadas</a>
                <a href="{% url 'crear_tag' %}">tags</a>
                <a href="{% url 'compartir' %}">compartir</a>
                <br>

                <a href="{% url 'salir' %}">Salir</a>
        </ul>
</div>
<div class="col-9 border">
        <div class="navbar">
        </div>

        {% block contenidos %}
                
    TODO: Hay que hacer el sistema de login para que se guarde el usuario para poder filtrar después
        {% endblock %}
</div>        



</div>


</body>
</html>

sylvia/pruebas/templates/pruebas/preview-prueba.html
{% extends './index.html' %}


{% block contenidos %}
<h2>Preview</h2>
{% for prueba in contenedor_final %}
<hr>
        {% for enum,pregunta in prueba %}
               
                {{enum}}.-{{ pregunta.enunciado }}<br>
                {% for abc,alt in pregunta.alternativas_de_la_pregunta %}
                {{abc}}) {{alt.texto}}.-  <br>
                {% endfor %}
        {% endfor %}

       

      
{% endfor %}
<a href="{% url 'generar_pdf' %}" class="btn btn-default">generar pdf</a>
{% endblock %}

sylvia/pruebas/templates/pruebas/tabla-compartidos.html
<table class="table table-dark">
    <thead>
      <tr>
        <th>Usuario</th>
        <th>Tag</th>
      </tr>
    </thead>
    <tbody>
        {% for t in tabla_compartidos %}
      <tr>
        <td>{{t.usuario_a_compartir}}</td>
        <td>{{t.tag_a_compartir}}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>